title: Master Jet Pressure Washing Ltd.
description: >-
  Master Jet Pressure Washing Ltd. is an industry leader in power and hot pressure washing. Since 2005, we have grown into one of the largest commercial, industrial and residential exterior cleaning businesses in Alberta. We provide services in Edmonton and surrounding areas including Red Deer, Fort McMurray, Leduc, Fort Saskatchewan and St. Albert.
keywords: >-
  Pressure washing, power washing, Commercial building washes, 
  pavement cleaning, concrete cleaning, gum spot removal, dumpster cleaning, 
  compactor cleaning, building exterior cleaning, warehouse cleaning,
  residential building cleaning
url: "https://masterjet.ca"
phone: 780-239-9979
email: amawer@shaw.ca

exclude: 
  -
    _site-text
  -
    _designs
    
defaults:
  - # All Pages have layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap