title: Master Jet Pressure Washing Ltd.
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: >-
  Pressure washing, power washing, Commercial building washes, 
  pavement cleaning, concrete cleaning, gum spot removal, dumpster cleaning, 
  compactor cleaning, building exterior cleaning, warehouse cleaning,
  residential building cleaning
url: ""
phone: 780-239-9979
email: amawer@shaw.ca
formspree:

exclude: 
  -
    _site-text
  -
    _designs
defaults:
  - # All Pages have layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"